# Generated by Django 4.2.3 on 2023-08-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fileapi", "0003_file_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="filename",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
