# Generated by Django 4.2.3 on 2023-08-08 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fileapi", "0005_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="folder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fileapi.folder",
            ),
        ),
    ]
