# Generated by Django 4.2.3 on 2023-08-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameapi", "0002_sudoku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sudoku",
            name="current_level",
            field=models.IntegerField(default=1),
        ),
    ]
